=== danielagoncalves12/ICD/ICD_BatalhaNaval/src/main/java/protocol/PlayerInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Data">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Player" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Name" type="xs:string" />
              <xs:element name="Password" type="xs:string" />
			  <xs:element name="Color" type="xs:string"/>
			  <xs:element name="Date" type="xs:string"/>
              <xs:element name="Picture" type="xs:string"/>
			  <xs:element name="WinsNumber" type="xs:int"/>
			  <xs:element name="AverageTime" type="xs:double"/>	
            </xs:sequence>
			<xs:attribute name="Username" type="xs:string" use="required"/>
          </xs:complexType>	 
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== danielagoncalves12/ICD/ICD_BatalhaNaval/src/main/java/protocol/PlayerInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><Data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="PlayerInfo.xsd">
	<Player Username="Dannie">
		<Name>Dannie12</Name>
		<Password>5BA4A4AAD2A0FBDF013B98B8B9657E83</Password>
		<Color>#e368c1</Color>
		<Date>2000-06-12</Date>
		<Picture>Dannie.png</Picture>
		<WinsNumber>28</WinsNumber>
	</Player>
	<Player Username="Nick">
		<Name>Nick</Name>
		<Password>9CFA7AEFCC61936B70AAEC6729329EDA</Password>
		<Color>#94bfe3</Color>
		<Date>2010-01-01</Date>
		<Picture>Nick.png</Picture>
		<WinsNumber>43</WinsNumber>
	</Player>
	<Player Username="teste1">
		<Name>GoingOn</Name>
		<Password>698DC19D489C4E4DB73E28A713EAB07B</Password>
		<Color>#8892ea</Color>
		<Date>2022-05-29</Date>
		<Picture>default.png</Picture>
		<WinsNumber>21</WinsNumber>
	</Player>
	<Player Username="teste2">
		<Name>xXTryHardXx</Name>
		<Password>698DC19D489C4E4DB73E28A713EAB07B</Password>
		<Color>#8892ea</Color>
		<Date>2022-05-29</Date>
		<Picture>icd.png</Picture>
		<WinsNumber>10</WinsNumber>
	</Player>
	<Player Username="teste3">
		<Name>reallu</Name>
		<Password>698DC19D489C4E4DB73E28A713EAB07B</Password>
		<Color>#8892ea</Color>
		<Date>2022-05-29</Date>
		<Picture>dog.jpg</Picture>
		<WinsNumber>5</WinsNumber>
	</Player>
	<Player Username="teste4">
		<Name>Anya</Name>
		<Password>698DC19D489C4E4DB73E28A713EAB07B</Password>
		<Color>#8892ea</Color>
		<Date>2022-05-29</Date>
		<Picture>girl.png</Picture>
		<WinsNumber>2</WinsNumber>
	</Player>
	<Player Username="teste5">
		<Name>Mapped</Name>
		<Password>698DC19D489C4E4DB73E28A713EAB07B</Password>
		<Color>#8892ea</Color>
		<Date>2022-05-29</Date>
		<Picture>mapped.png</Picture>
		<WinsNumber>12</WinsNumber>
	</Player>
	<Player Username="teste6">
		<Name>Pandora</Name>
		<Password>698DC19D489C4E4DB73E28A713EAB07B</Password>
		<Color>#8892ea</Color>
		<Date>2022-05-29</Date>
		<Picture>pandora.png</Picture>
		<WinsNumber>12</WinsNumber>
	</Player>
	<Player Username="teste7">
		<Name>Gamerz19</Name>
		<Password>698DC19D489C4E4DB73E28A713EAB07B</Password>
		<Color>#8892ea</Color>
		<Date>2022-05-29</Date>
		<Picture>logo.png</Picture>
		<WinsNumber>4</WinsNumber>
	</Player>
	<Player Username="teste8">
		<Name>Wazowski</Name>
		<Password>698DC19D489C4E4DB73E28A713EAB07B</Password>
		<Color>#8892ea</Color>
		<Date>2002-05-29</Date>
		<Picture>mike.png</Picture>
		<WinsNumber>12</WinsNumber>
	</Player>
	<Player Username="JohnGames">
		<Name>JohnGames</Name>
		<Password>698DC19D489C4E4DB73E28A713EAB07B</Password>
		<Color>#52e2d8</Color>
		<Date>2022-06-14</Date>
		<Picture>shrek.png</Picture>
		<WinsNumber>14</WinsNumber>
	</Player>
	<Player Username="Dann">
		<Name>Dann</Name>
		<Password>E9F49E0ADDDF4EDBB14C2832DA3283A2</Password>
		<Color>#000000</Color>
		<Date>2022-06-06</Date>
		<Picture>default.png</Picture>
		<WinsNumber>0</WinsNumber>
	</Player>
</Data>
