=== danielagoncalves12/ICD/tp1/src/main/webapp/xml/PlayerInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Data">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Player" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Nickname" type="xs:string" />
              <xs:element name="Password" type="xs:string" />
              <xs:element name="Picture" type="xs:string"/>
			<!--  <xs:element name="WinsNumber" type="xs:int"/> -->
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== danielagoncalves12/ICD/tp1/src/main/webapp/xml/PlayerInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><Data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="PlayerInfo.xsd">
   <Player>
      <Nickname>Nick</Nickname>
      <Password>games</Password>
      <Picture>teste</Picture>
   </Player>
   <Player>
      <Nickname>Daniela</Nickname>
      <Password>Goncalves</Password>
      <Picture>picture</Picture>
   </Player>
<Player><Nickname>Ze</Nickname><Password>manel</Password><Picture>default/photo.png</Picture></Player><Player><Nickname>Dannie</Nickname><Password>senha</Password><Picture>default/photo.png</Picture></Player><Player><Nickname>Teste</Nickname><Password>teste</Password><Picture>teste</Picture></Player></Data>
