=== danielagoncalves12/ICD/ICD_BatalhaNaval/src/main/webapp/xml/PlayerInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Data">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Player" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Name" type="xs:string" />
              <xs:element name="Password" type="xs:string" />
              <xs:element name="Picture" type="xs:string"/>
			  <xs:element name="WinsNumber" type="xs:int"/>
            </xs:sequence>
			<xs:attribute name="Nickname" type="xs:string" use="required"/>
          </xs:complexType>	 
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== danielagoncalves12/ICD/ICD_BatalhaNaval/src/main/webapp/xml/PlayerInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><Data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="PlayerInfo.xsd">
	<Player Nickname="Dannie">
		<Name>Daniela</Name>
		<Password>5BA4A4AAD2A0FBDF013B98B8B9657E83</Password>
		<Picture>dannie.png</Picture>
		<WinsNumber>6</WinsNumber>
	</Player>
	<Player Nickname="Nick">
		<Name>Nick</Name>
		<Password>9CFA7AEFCC61936B70AAEC6729329EDA</Password>
		<Picture>alex.jpeg</Picture>
		<WinsNumber>17</WinsNumber>
	</Player>
	<Player Nickname="aaaa">
		<Name>asdasd</Name>
		<Password>66526FBC9691BFA753B9D86516D0D2B1</Password>
		<Picture>default.png</Picture>
		<WinsNumber>0</WinsNumber>
	</Player>
	<Player Nickname="teste">
		<Name>aaaa</Name>
		<Password>47BCE5C74F589F4867DBD57E9CA9F808</Password>
		<Picture>default.png</Picture>
		<WinsNumber>0</WinsNumber>
	</Player>
<Player Nickname="Ola"><Name>ola</Name><Password>A2E63EE01401AAECA78BE023DFBB8C59</Password><Picture>default.png</Picture><WinsNumber>0</WinsNumber></Player><Player Nickname="teste123"><Name>teste123</Name><Password>AA1BF4646DE67FD9086CF6C79007026C</Password><Picture>default.png</Picture><WinsNumber>0</WinsNumber></Player></Data>
